app = "simnux"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"
  
  [build.args]
    BACKEND_URL = ""

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80
