app = "simnux-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8001"
  ALLOWED_ORIGINS = ""

[[services]]
  protocol = "tcp"
  internal_port = 8001

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80
